runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /static
  static_dir: build/static
  secure: always
- url: /favicon.ico
  static_files: build/favicon.ico
  upload: build/favicon.ico
  secure: always
- url: /manifest.json
  static_files: build/manifest.json
  upload: build/manifest.json
  secure: always
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
