export const GET_OK_ACCESS_TOKEN_SUCCESS = 'GET_OK_ACCESS_TOKEN_SUCCESS'
export const GET_OK_ACCESS_TOKEN_STARTED = 'GET_OK_ACCESS_TOKEN_STARTED'
export const GET_OK_ACCESS_TOKEN_FAILURE = 'GET_OK_ACCESS_TOKEN_FAILURE'

export const GET_GOOGLE_ACCESS_TOKEN_SUCCESS = 'GET_GOOGLE_ACCESS_TOKEN_SUCCESS'
export const GET_GOOGLE_ACCESS_TOKEN_STARTED = 'GET_GOOGLE_ACCESS_TOKEN_STARTED'
export const GET_GOOGLE_ACCESS_TOKEN_FAILURE = 'GET_GOOGLE_ACCESS_TOKEN_FAILURE'

export const GET_HOME_DATA_STARTED = 'GET_HOME_DATA_STARTED'
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS'
export const GET_HOME_DATA_FAILURE = 'GET_HOME_DATA_FAILURE'

export const GET_COURSE_DATA_STARTED = 'GET_COURSE_DATA_STARTED'
export const GET_COURSE_DATA_SUCCESS = 'GET_COURSE_DATA_SUCCESS'
export const GET_COURSE_DATA_FAILURE = 'GET_COURSE_DATA_FAILURE'
