export const GET_OK_ACCESS_TOKEN_SUCCESS = 'GET_OK_ACCESS_TOKEN_SUCCESS'
export const GET_OK_ACCESS_TOKEN_STARTED = 'GET_OK_ACCESS_TOKEN_STARTED'
export const GET_OK_ACCESS_TOKEN_FAILURE = 'GET_OK_ACCESS_TOKEN_FAILURE'
export const CLEAR_SESSION = 'CLEAR_SESSION'

export const GET_GOOGLE_ACCESS_TOKEN_SUCCESS = 'GET_GOOGLE_ACCESS_TOKEN_SUCCESS'
export const GET_GOOGLE_ACCESS_TOKEN_FAILURE = 'GET_GOOGLE_ACCESS_TOKEN_FAILURE'

export const GET_HOME_DATA_STARTED = 'GET_HOME_DATA_STARTED'
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS'
export const GET_HOME_DATA_FAILURE = 'GET_HOME_DATA_FAILURE'

export const CREATE_COURSE_STARTED = 'CREATE_COURSE_STARTED'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE'

export const CREATE_PIAZZA_BOT_SUCCESS = 'CREATE_PIAZZA_BOT_SUCCESS'
export const CREATE_PIAZZA_BOT_FAILURE = 'CREATE_COURSE_FAILURE'

export const GET_COURSE_DATA_STARTED = 'GET_COURSE_DATA_STARTED'
export const GET_COURSE_DATA_SUCCESS = 'GET_COURSE_DATA_SUCCESS'
export const GET_COURSE_DATA_FAILURE = 'GET_COURSE_DATA_FAILURE'

export const GET_LECTURE_DATA_STARTED = 'GET_LECTURE_DATA_STARTED'
export const GET_LECTURE_DATA_SUCCESS = 'GET_LECTURE_DATA_SUCCESS'
export const GET_LECTURE_DATA_FAILURE = 'GET_LECTURE_DATA_FAILURE'

export const GET_VIDEO_DATA_STARTED = 'GET_VIDEO_DATA_STARTED'
export const GET_VIDEO_DATA_SUCCESS = 'GET_VIDEO_DATA_SUCCESS'
export const GET_VIDEO_DATA_FAILURE = 'GET_VIDEO_DATA_FAILURE'

export const GET_TRANSCRIPT_STARTED = 'GET_TRANSCRIPT_STARTED'
export const GET_TRANSCRIPT_SUCCESS = 'GET_TRANSCRIPT_SUCCESS'
export const GET_TRANSCRIPT_FAILURE = 'GET_TRANSCRIPT_FAILURE'

export const GET_ROLE_STARTED = 'GET_ROLE_STARTED'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE'
export const GET_ROLE_NO_COURSE_FOUND = 'GET_ROLE_NO_COURSE_FOUND'
